app_home_index:
    path:     /
    defaults: { _controller: AppBundle:Home:index }
app_home_notif_video:
    path:     /notif/video.html
    defaults: { _controller: AppBundle:Home:notifvideo }
app_home_notif_url:
    path:     /notif/url.html
    defaults: { _controller: AppBundle:Home:notifUrl }
app_home_notif_user_video:
    path:     /notif/user_video.html
    defaults: { _controller: AppBundle:Home:notifUservideo }
app_home_notif_user:
    path:     /notif/user.html
    defaults: { _controller: AppBundle:Home:notifUser }
app_home_notif_category:
    path:     /notif/category.html
    defaults: { _controller: AppBundle:Home:notifCategory }
api_home_api_device:
    path:   /api/device/{tkn}/{token}/{purchase}/
    defaults: { _controller: AppBundle:Home:api_device }
app_support_index:
    path:     /support/index.html
    defaults: { _controller: AppBundle:Support:index }
app_support_view:
    path:     /support/view/{id}.html
    defaults: { _controller: AppBundle:Support:view }
app_support_delete:
    path:     /support/delete/{id}.html
    defaults: { _controller: AppBundle:Support:delete }
api_support_add:
    path:     /api/support/add/{token}/{purchase}/
    defaults: { _controller: AppBundle:Support:api_add }
    methods: POST







#category video
app_category_index:
    path: /category/video/index.html
    defaults: { _controller: AppBundle:Category:index}

app_category_add:
    path: /category/video/add.html
    defaults: { _controller: AppBundle:Category:add}

app_category_edit:
    path: /category/video/edit/{id}.html
    defaults: { _controller: AppBundle:Category:edit}
    requirements:
        id:  \d+

app_category_delete:
    path: /category/video/delete/{id}.html
    defaults: { _controller: AppBundle:Category:delete}
    requirements:
        id:  \d+

app_category_up:
    path: /category/video/up/{id}.html
    defaults: { _controller: AppBundle:Category:up}
    requirements:
        id:  \d+

app_category_down:
    path: /category/video/down/{id}.html
    defaults: { _controller: AppBundle:Category:down}
    requirements:
        id:  \d+
api_category_all:
    path:     /api/category/video/all/{token}/{purchase}/
    defaults: { _controller: AppBundle:Category:api_all }
#version
app_version_add:
    path: /version/add.html
    defaults: { _controller: AppBundle:Version:add}
app_version_index:
    path: /version/index.html
    defaults: { _controller: AppBundle:Version:index}
app_version_edit:
    path: /version/edit/{id}.html
    defaults: { _controller: AppBundle:Version:edit}
    requirements:
        id:  \d+
app_version_delete:
    path: /version/delete/{id}.html
    defaults: { _controller: AppBundle:Version:delete}
    requirements:
        id:  \d+
api_version_check:
    path: /api/version/check/{code}/{token}/{purchase}/
    defaults: { _controller: AppBundle:Version:api_check}
    requirements:
        code:  \d+

#video
app_video_add:
    path: /video/add.html
    defaults: { _controller: AppBundle:Video:add}
app_video_index:
    path: /video/index.html
    defaults: { _controller: AppBundle:Video:index}
app_video_reviews:
    path: /video/reviews.html
    defaults: { _controller: AppBundle:Video:reviews}
app_video_review:
    path: /video/review/{id}.html
    defaults: { _controller: AppBundle:Video:review}
    requirements:
        id:  \d+
app_video_edit:
    path: /video/{id}.html
    defaults: { _controller: AppBundle:Video:edit}
    requirements:
        id:  \d+
app_video_view:
    path: /video/view/{id}.html
    defaults: { _controller: AppBundle:Video:view}
    requirements:
        id:  \d+
app_video_delete:
    path: /video/delete/{id}.html
    defaults: { _controller: AppBundle:Video:delete}
    requirements:
        id:  \d+
api_video_all:
    path:     /api/video/all/{page}/{order}/{language}/{token}/{purchase}/
    defaults: { _controller: AppBundle:Video:api_all }
    requirements:
        page: \d+
api_video_my:
    path:     /api/video/my/{page}/{user}/{token}/{purchase}/
    defaults: { _controller: AppBundle:Video:api_my }
    requirements:
        page: \d+
api_video_by_category:
    path:     /api/video/by/category/{page}/{order}/{language}/{category}/{token}/{purchase}/
    defaults: { _controller: AppBundle:Video:api_by_category }
    requirements:
        category: \d+
        page: \d+
api_video_by_query:
    path:     /api/video/by/query/{order}/{language}/{page}/{query}/{token}/{purchase}/
    defaults: { _controller: AppBundle:Video:api_by_query }
api_video_by_random:
    path:     /api/video/by/random/{language}/{token}/{purchase}/
    defaults: { _controller: AppBundle:Video:api_by_random }
    requirements:
api_video_add_copied:
    path:     /api/video/add/copied/{token}/{purchase}/
    defaults: { _controller: AppBundle:Video:api_add_copied }
api_video_upload:
    path:     /api/video/upload/{token}/{purchase}/
    defaults: { _controller: AppBundle:Video:api_upload}
api_video_by_user:
    path:     /api/video/by/user/{page}/{order}/{language}/{user}/{token}/{purchase}/
    defaults: { _controller: AppBundle:Video:api_by_user }
    requirements:
        user: \d+
        page: \d+
api_video_by_me:
    path:     /api/video/by/me/{page}/{user}/{token}/{purchase}/
    defaults: { _controller: AppBundle:Video:api_by_me }
    requirements:
        user: \d+
api_video_by_follow:
    path:     /api/video/by/follow/{page}/{language}/{user}/{token}/{purchase}/
    defaults: { _controller: AppBundle:Video:api_by_follow }
    requirements:
        page: \d+
        user: \d+
#reactions 

api_video_add_like:
    path:     /api/video/add/like/{token}/{purchase}/
    defaults: { _controller: AppBundle:Video:api_add_like }
    
api_video_add_love:
    path:     /api/video/add/love/{token}/{purchase}/
    defaults: { _controller: AppBundle:Video:api_add_love }

api_video_add_angry:
    path:     /api/video/add/angry/{token}/{purchase}/
    defaults: { _controller: AppBundle:Video:api_add_angry }

api_video_add_sad:
    path:     /api/video/add/sad/{token}/{purchase}/
    defaults: { _controller: AppBundle:Video:api_add_sad }

api_video_add_haha:
    path:     /api/video/add/haha/{token}/{purchase}/
    defaults: { _controller: AppBundle:Video:api_add_haha }

api_video_add_woow:
    path:     /api/video/add/woow/{token}/{purchase}/
    defaults: { _controller: AppBundle:Video:api_add_woow }



api_video_delete_like:
    path:     /api/video/delete/like/{token}/{purchase}/
    defaults: { _controller: AppBundle:Video:api_delete_like }
    
api_video_delete_love:
    path:     /api/video/delete/love/{token}/{purchase}/
    defaults: { _controller: AppBundle:Video:api_delete_love }

api_video_delete_angry:
    path:     /api/video/delete/angry/{token}/{purchase}/
    defaults: { _controller: AppBundle:Video:api_delete_angry }

api_video_delete_sad:
    path:     /api/video/delete/sad/{token}/{purchase}/
    defaults: { _controller: AppBundle:Video:api_delete_sad }

api_video_delete_haha:
    path:     /api/video/delete/haha/{token}/{purchase}/
    defaults: { _controller: AppBundle:Video:api_delete_haha }

api_video_delete_woow:
    path:     /api/video/delete/woow/{token}/{purchase}/
    defaults: { _controller: AppBundle:Video:api_delete_woow }






#language 
app_language_add:
    path: /language/add.html
    defaults: { _controller: AppBundle:Language:add}
app_language_index:
    path: /language/index.html
    defaults: { _controller: AppBundle:Language:index}
app_language_edit:
    path: /language/edit/{id}.html
    defaults: { _controller: AppBundle:Language:edit}
    requirements:
        id:  \d+
app_language_delete:
    path: /language/delete/{id}.html
    defaults: { _controller: AppBundle:Language:delete}
    requirements:
        id:  \d+
app_language_up:
    path: /language/up/{id}.html
    defaults: { _controller: AppBundle:Language:up}
    requirements:
        id:  \d+
app_language_down:
    path: /language/down/{id}.html
    defaults: { _controller: AppBundle:Language:down}
    requirements:
        id:  \d+
api_language_all:
    path:     /api/language/all/{token}/{purchase}/
    defaults: { _controller: AppBundle:Language:api_all }
#comment
app_comment_delete:
    path:     /comment/delete/{id}.html
    defaults: { _controller: AppBundle:Comment:delete }
    requirements:
        id:  \d+
app_comment_hide:
    path:     /comment/hide/{id}.html
    defaults: { _controller: AppBundle:Comment:hide }
    requirements:
        id:  \d+  
app_comment_index:
    path:     /comment/index.html
    defaults: { _controller: AppBundle:Comment:index }
api_comment_add:
    path:     /api/comment/add/{token}/{purchase}/
    defaults: { _controller: AppBundle:Comment:api_add }
    methods: POST
api_comment_list:
    path:     /api/comment/list/{id}/{token}/{purchase}/
    defaults: { _controller: AppBundle:Comment:api_list }
    requirements:
        id:  \d+  
